version: '3'
services:
  random-4k:
    build: .
    container_name: random-4k-image
    network_mode: bridge
    ports:
      - "12673:3000"
    volumes:
      - /mnt/user/appdata/docker/random-4k/server.js:/app/server.js:ro
    environment:
      - NODE_ENV=production
      - R2_ACCESS_KEY_ID=你的R2访问密钥ID
      - R2_SECRET_ACCESS_KEY=你的R2访问密钥
      - R2_BUCKET=backgroudimage
    restart: always

networks:
  default:
    driver: bridge